kind: pipeline
type: docker
name: 构建站点文件

steps:
  - name: pnpm构建
    image: node:18-alpine
    volumes:
      - name: cache
        path: /.pnpm-store
    commands:
      - sed -i 's#https\?://dl-cdn.alpinelinux.org/alpine#https://mirrors.tuna.tsinghua.edu.cn/alpine#g' /etc/apk/repositories
      - apk update && apk add git
      - corepack enable
      - corepack prepare pnpm@latest-9
      - pnpm config set store-dir /.pnpm-store
      - pnpm config set registry https://registry.npmmirror.com
      - pnpm install
      - pnpm run docs:build

volumes:
  - name: cache
    host:
      path: /root/drone/pnpm/cache