language: node_js

node_js:
  - 10.13.0

before_script:
  - export TZ='Asia/Shanghai'
  - yarn

script:
  - yarn build

after_script:
  - cd ./pulic
  - git init
  - git config user.name ${USER_NAME}
  - git config user.email ${USER_EMAIL}
  - cp ../CNAME ./
  - git add .
  - git commit -m "build and update"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

cache:
  directories:
    - node_modules

branches:
  only:
    - master